version: '3.8'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-container
    restart: always
    env_file:
      - .env.development  # Load environment variables from .env file
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - express-app
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: