version: '3.8'

services:
  backend:
    build: ./
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=userdata
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run serve"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdata
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: