version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "xchangedb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    env_file:
      - .env.development
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-container
    restart: always
    env_file:
      - .env.development
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - express-app
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge